import firebase_admin
from firebase_admin import credentials
from firebase_admin import auth

cred = credentials.Certificate("./fluent-webbing-257713-firebase-adminsdk-ks6cb-2dd1be74c4.json")
firebase_admin.initialize_app(cred)


def verifyIdToken(idToken):
    try:
        decoded_token = auth.verify_id_token(idToken)
        return decoded_token
    except:
        return None

t = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjRhOWEzMGI5ZThkYTMxNjY2YTY3NTRkZWZlZDQxNzQzZjJlN2FlZWEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZmx1ZW50LXdlYmJpbmctMjU3NzEzIiwiYXVkIjoiZmx1ZW50LXdlYmJpbmctMjU3NzEzIiwiYXV0aF90aW1lIjoxNTc0ODg0NzAxLCJ1c2VyX2lkIjoibEpyTEs2UkJyWFZFVzJrNEVJSHZsZ05yS3J3MiIsInN1YiI6ImxKckxLNlJCclhWRVcyazRFSUh2bGdOcktydzIiLCJpYXQiOjE1NzQ4ODg5ODEsImV4cCI6MTU3NDg5MjU4MSwiZW1haWwiOiJkc2FkZnNhQGRmc2FkZi5ubyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJkc2FkZnNhQGRmc2FkZi5ubyJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.FutIy8tF4vUJ-kJ6suSfzaqpvd8fLo6yUtINwhOYwlemVjbKsCUbx-E9VZOiKyBEOCzXHfj5lvkt7jT-h_ROVC7Z1MewI3lDMeTuD_EBEBWXrJ8waMgy5XR0MuqQTstcFfxUGscheZ8KS78GDzDGyhS6OfUUApWTbSYLJYaxnMEMiHzpZFq8D4YBOekKqJfKdQkEIrhy6_U3atYXmaSAYYq06Jt-jUT9TqMUkXxCu9xgHGPW0CIFe8MG9dWFGck5O7J54xgH2H3Vam9UyBhzn1dDlQGbvlpXViIYJj_fqV5ptYVeMu98lSYGEyNzARqDsIU0zsBoTY-AIFfOZhmoIQ"

print(verifyIdToken(t))